(cl:in-package aerostack_msgs-srv)
(cl:export '(REACTIVE_BEHAVIORS-VAL
          REACTIVE_BEHAVIORS
          ACTIVE_BEHAVIORS-VAL
          ACTIVE_BEHAVIORS
          HIGH_PRIORITY_BEHAVIORS-VAL
          HIGH_PRIORITY_BEHAVIORS
          LOW_PRIORITY_BEHAVIORS-VAL
          LOW_PRIORITY_BEHAVIORS
          ACK-VAL
          ACK
          ERROR_MESSAGE-VAL
          ERROR_MESSAGE
))