// Generated by gencpp from file aerostack_msgs/BehaviorCommandPriority.msg
// DO NOT EDIT!


#ifndef AEROSTACK_MSGS_MESSAGE_BEHAVIORCOMMANDPRIORITY_H
#define AEROSTACK_MSGS_MESSAGE_BEHAVIORCOMMANDPRIORITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aerostack_msgs
{
template <class ContainerAllocator>
struct BehaviorCommandPriority_
{
  typedef BehaviorCommandPriority_<ContainerAllocator> Type;

  BehaviorCommandPriority_()
    : name()
    , arguments()
    , priority(0)  {
    }
  BehaviorCommandPriority_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , arguments(_alloc)
    , priority(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _arguments_type;
  _arguments_type arguments;

   typedef uint8_t _priority_type;
  _priority_type priority;





  typedef boost::shared_ptr< ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator> const> ConstPtr;

}; // struct BehaviorCommandPriority_

typedef ::aerostack_msgs::BehaviorCommandPriority_<std::allocator<void> > BehaviorCommandPriority;

typedef boost::shared_ptr< ::aerostack_msgs::BehaviorCommandPriority > BehaviorCommandPriorityPtr;
typedef boost::shared_ptr< ::aerostack_msgs::BehaviorCommandPriority const> BehaviorCommandPriorityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator1> & lhs, const ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.arguments == rhs.arguments &&
    lhs.priority == rhs.priority;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator1> & lhs, const ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aerostack_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76d1351585bd0321d075da8186c1c24f";
  }

  static const char* value(const ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76d1351585bd0321ULL;
  static const uint64_t static_value2 = 0xd075da8186c1c24fULL;
};

template<class ContainerAllocator>
struct DataType< ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aerostack_msgs/BehaviorCommandPriority";
  }

  static const char* value(const ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request to execute a behavior with a set of arguments\n"
"\n"
"string name       # Behavior name\n"
"string arguments  # Arguments of the behavior\n"
"uint8 priority	  # Priority of the behavior\n"
;
  }

  static const char* value(const ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.arguments);
      stream.next(m.priority);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BehaviorCommandPriority_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aerostack_msgs::BehaviorCommandPriority_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "arguments: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.arguments);
    s << indent << "priority: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.priority);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AEROSTACK_MSGS_MESSAGE_BEHAVIORCOMMANDPRIORITY_H
