// Generated by gencpp from file aerostack_msgs/InhibitBehavior.msg
// DO NOT EDIT!


#ifndef AEROSTACK_MSGS_MESSAGE_INHIBITBEHAVIOR_H
#define AEROSTACK_MSGS_MESSAGE_INHIBITBEHAVIOR_H

#include <ros/service_traits.h>


#include <aerostack_msgs/InhibitBehaviorRequest.h>
#include <aerostack_msgs/InhibitBehaviorResponse.h>


namespace aerostack_msgs
{

struct InhibitBehavior
{

typedef InhibitBehaviorRequest Request;
typedef InhibitBehaviorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InhibitBehavior
} // namespace aerostack_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aerostack_msgs::InhibitBehavior > {
  static const char* value()
  {
    return "bedda506d9d7ec53f524c786f168f2d6";
  }

  static const char* value(const ::aerostack_msgs::InhibitBehavior&) { return value(); }
};

template<>
struct DataType< ::aerostack_msgs::InhibitBehavior > {
  static const char* value()
  {
    return "aerostack_msgs/InhibitBehavior";
  }

  static const char* value(const ::aerostack_msgs::InhibitBehavior&) { return value(); }
};


// service_traits::MD5Sum< ::aerostack_msgs::InhibitBehaviorRequest> should match
// service_traits::MD5Sum< ::aerostack_msgs::InhibitBehavior >
template<>
struct MD5Sum< ::aerostack_msgs::InhibitBehaviorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aerostack_msgs::InhibitBehavior >::value();
  }
  static const char* value(const ::aerostack_msgs::InhibitBehaviorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aerostack_msgs::InhibitBehaviorRequest> should match
// service_traits::DataType< ::aerostack_msgs::InhibitBehavior >
template<>
struct DataType< ::aerostack_msgs::InhibitBehaviorRequest>
{
  static const char* value()
  {
    return DataType< ::aerostack_msgs::InhibitBehavior >::value();
  }
  static const char* value(const ::aerostack_msgs::InhibitBehaviorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aerostack_msgs::InhibitBehaviorResponse> should match
// service_traits::MD5Sum< ::aerostack_msgs::InhibitBehavior >
template<>
struct MD5Sum< ::aerostack_msgs::InhibitBehaviorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aerostack_msgs::InhibitBehavior >::value();
  }
  static const char* value(const ::aerostack_msgs::InhibitBehaviorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aerostack_msgs::InhibitBehaviorResponse> should match
// service_traits::DataType< ::aerostack_msgs::InhibitBehavior >
template<>
struct DataType< ::aerostack_msgs::InhibitBehaviorResponse>
{
  static const char* value()
  {
    return DataType< ::aerostack_msgs::InhibitBehavior >::value();
  }
  static const char* value(const ::aerostack_msgs::InhibitBehaviorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AEROSTACK_MSGS_MESSAGE_INHIBITBEHAVIOR_H
