// Generated by gencpp from file aerostack_msgs/QueryBeliefRequest.msg
// DO NOT EDIT!


#ifndef AEROSTACK_MSGS_MESSAGE_QUERYBELIEFREQUEST_H
#define AEROSTACK_MSGS_MESSAGE_QUERYBELIEFREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aerostack_msgs
{
template <class ContainerAllocator>
struct QueryBeliefRequest_
{
  typedef QueryBeliefRequest_<ContainerAllocator> Type;

  QueryBeliefRequest_()
    : query()  {
    }
  QueryBeliefRequest_(const ContainerAllocator& _alloc)
    : query(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _query_type;
  _query_type query;





  typedef boost::shared_ptr< ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator> const> ConstPtr;

}; // struct QueryBeliefRequest_

typedef ::aerostack_msgs::QueryBeliefRequest_<std::allocator<void> > QueryBeliefRequest;

typedef boost::shared_ptr< ::aerostack_msgs::QueryBeliefRequest > QueryBeliefRequestPtr;
typedef boost::shared_ptr< ::aerostack_msgs::QueryBeliefRequest const> QueryBeliefRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator1> & lhs, const ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator2> & rhs)
{
  return lhs.query == rhs.query;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator1> & lhs, const ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aerostack_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6490a46152f373285fe18f491ed93702";
  }

  static const char* value(const ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6490a46152f37328ULL;
  static const uint64_t static_value2 = 0x5fe18f491ed93702ULL;
};

template<class ContainerAllocator>
struct DataType< ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aerostack_msgs/QueryBeliefRequest";
  }

  static const char* value(const ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# SERVICE TYPE: 	QueryBelief\n"
"# ------------------------------------------------------------------------------\n"
"# This service queries the belief memory belief memory, returning a boolean\n"
"# value and a list of variables substituted to unify the query\n"
"\n"
"\n"
"string query           # query expression that may contain variables\n"
;
  }

  static const char* value(const ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.query);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryBeliefRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aerostack_msgs::QueryBeliefRequest_<ContainerAllocator>& v)
  {
    s << indent << "query: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.query);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AEROSTACK_MSGS_MESSAGE_QUERYBELIEFREQUEST_H
