// Generated by gencpp from file aerostack_msgs/SetControlMode.msg
// DO NOT EDIT!


#ifndef AEROSTACK_MSGS_MESSAGE_SETCONTROLMODE_H
#define AEROSTACK_MSGS_MESSAGE_SETCONTROLMODE_H

#include <ros/service_traits.h>


#include <aerostack_msgs/SetControlModeRequest.h>
#include <aerostack_msgs/SetControlModeResponse.h>


namespace aerostack_msgs
{

struct SetControlMode
{

typedef SetControlModeRequest Request;
typedef SetControlModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetControlMode
} // namespace aerostack_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aerostack_msgs::SetControlMode > {
  static const char* value()
  {
    return "57952eae1ac185199e7813d328b76fe5";
  }

  static const char* value(const ::aerostack_msgs::SetControlMode&) { return value(); }
};

template<>
struct DataType< ::aerostack_msgs::SetControlMode > {
  static const char* value()
  {
    return "aerostack_msgs/SetControlMode";
  }

  static const char* value(const ::aerostack_msgs::SetControlMode&) { return value(); }
};


// service_traits::MD5Sum< ::aerostack_msgs::SetControlModeRequest> should match
// service_traits::MD5Sum< ::aerostack_msgs::SetControlMode >
template<>
struct MD5Sum< ::aerostack_msgs::SetControlModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aerostack_msgs::SetControlMode >::value();
  }
  static const char* value(const ::aerostack_msgs::SetControlModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aerostack_msgs::SetControlModeRequest> should match
// service_traits::DataType< ::aerostack_msgs::SetControlMode >
template<>
struct DataType< ::aerostack_msgs::SetControlModeRequest>
{
  static const char* value()
  {
    return DataType< ::aerostack_msgs::SetControlMode >::value();
  }
  static const char* value(const ::aerostack_msgs::SetControlModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aerostack_msgs::SetControlModeResponse> should match
// service_traits::MD5Sum< ::aerostack_msgs::SetControlMode >
template<>
struct MD5Sum< ::aerostack_msgs::SetControlModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aerostack_msgs::SetControlMode >::value();
  }
  static const char* value(const ::aerostack_msgs::SetControlModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aerostack_msgs::SetControlModeResponse> should match
// service_traits::DataType< ::aerostack_msgs::SetControlMode >
template<>
struct DataType< ::aerostack_msgs::SetControlModeResponse>
{
  static const char* value()
  {
    return DataType< ::aerostack_msgs::SetControlMode >::value();
  }
  static const char* value(const ::aerostack_msgs::SetControlModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AEROSTACK_MSGS_MESSAGE_SETCONTROLMODE_H
