(cl:in-package mikrokopter_driver-msg)
(cl:export '(HEADER-VAL
          HEADER
          INTEGRATED_NICK-VAL
          INTEGRATED_NICK
          INTEGRATED_ROLL-VAL
          INTEGRATED_ROLL
          MEAN_ACCELERATION_NICK-VAL
          MEAN_ACCELERATION_NICK
          MEAN_ACCELERATION_ROLL-VAL
          MEAN_ACCELERATION_ROLL
          YAW-VAL
          YAW
          HEIGHT-VAL
          HEIGHT
          ACCELERATION_UP-VAL
          ACCELERATION_UP
          GAS-VAL
          GAS
          COMPASS-VAL
          COMPASS
          BATTERY_VOLTAGE-VAL
          BATTERY_VOLTAGE
          SENSOR_OK-VAL
          SENSOR_OK
          BACKUP_COMPASS_DEG-VAL
          BACKUP_COMPASS_DEG
          MOTOR_SET_POINTS-VAL
          MOTOR_SET_POINTS
          STICK_NICK-VAL
          STICK_NICK
          STICK_ROLL-VAL
          STICK_ROLL
          STICK_GIER-VAL
          STICK_GIER
          STICK_GAS-VAL
          STICK_GAS
          SERVO_NICK-VAL
          SERVO_NICK
          HOVER_GAS-VAL
          HOVER_GAS
          CURRENT-VAL
          CURRENT
          CAPACITY_USED-VAL
          CAPACITY_USED
          HEIGHT_SET_POINT-VAL
          HEIGHT_SET_POINT
          EXTERNAL_CONTROL-VAL
          EXTERNAL_CONTROL
          ANOTHER_UNUSED-VAL
          ANOTHER_UNUSED
          COMPASS_SET_POINT-VAL
          COMPASS_SET_POINT
          I2C_ERROR-VAL
          I2C_ERROR
          CAPACITY_MIN_OF_MAX_PWM-VAL
          CAPACITY_MIN_OF_MAX_PWM
          GPS_NICK-VAL
          GPS_NICK
          GPS_ROLL-VAL
          GPS_ROLL
))