// Generated by gencpp from file droneMsgsROS/CheckBehaviorGroupConsistencyResponse.msg
// DO NOT EDIT!


#ifndef DRONEMSGSROS_MESSAGE_CHECKBEHAVIORGROUPCONSISTENCYRESPONSE_H
#define DRONEMSGSROS_MESSAGE_CHECKBEHAVIORGROUPCONSISTENCYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace droneMsgsROS
{
template <class ContainerAllocator>
struct CheckBehaviorGroupConsistencyResponse_
{
  typedef CheckBehaviorGroupConsistencyResponse_<ContainerAllocator> Type;

  CheckBehaviorGroupConsistencyResponse_()
    : consistent(false)
    , error_message()
    , incompatibilities()  {
    }
  CheckBehaviorGroupConsistencyResponse_(const ContainerAllocator& _alloc)
    : consistent(false)
    , error_message(_alloc)
    , incompatibilities(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _consistent_type;
  _consistent_type consistent;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_message_type;
  _error_message_type error_message;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _incompatibilities_type;
  _incompatibilities_type incompatibilities;





  typedef boost::shared_ptr< ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CheckBehaviorGroupConsistencyResponse_

typedef ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<std::allocator<void> > CheckBehaviorGroupConsistencyResponse;

typedef boost::shared_ptr< ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse > CheckBehaviorGroupConsistencyResponsePtr;
typedef boost::shared_ptr< ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse const> CheckBehaviorGroupConsistencyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator1> & lhs, const ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator2> & rhs)
{
  return lhs.consistent == rhs.consistent &&
    lhs.error_message == rhs.error_message &&
    lhs.incompatibilities == rhs.incompatibilities;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator1> & lhs, const ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace droneMsgsROS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05f3d1c742882cb43cc85772530d2349";
  }

  static const char* value(const ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05f3d1c742882cb4ULL;
  static const uint64_t static_value2 = 0x3cc85772530d2349ULL;
};

template<class ContainerAllocator>
struct DataType< ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "droneMsgsROS/CheckBehaviorGroupConsistencyResponse";
  }

  static const char* value(const ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool consistent                     # if this value is true, the operation was done succesfully\n"
"string error_message                # text message describing a detected error\n"
"string[] incompatibilities          # list of names of behaviors that are incompatible with the requested behavior\n"
"\n"
;
  }

  static const char* value(const ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.consistent);
      stream.next(m.error_message);
      stream.next(m.incompatibilities);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckBehaviorGroupConsistencyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::droneMsgsROS::CheckBehaviorGroupConsistencyResponse_<ContainerAllocator>& v)
  {
    s << indent << "consistent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.consistent);
    s << indent << "error_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_message);
    s << indent << "incompatibilities[]" << std::endl;
    for (size_t i = 0; i < v.incompatibilities.size(); ++i)
    {
      s << indent << "  incompatibilities[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.incompatibilities[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONEMSGSROS_MESSAGE_CHECKBEHAVIORGROUPCONSISTENCYRESPONSE_H
