// Generated by gencpp from file droneMsgsROS/CheckBeliefFormat.msg
// DO NOT EDIT!


#ifndef DRONEMSGSROS_MESSAGE_CHECKBELIEFFORMAT_H
#define DRONEMSGSROS_MESSAGE_CHECKBELIEFFORMAT_H

#include <ros/service_traits.h>


#include <droneMsgsROS/CheckBeliefFormatRequest.h>
#include <droneMsgsROS/CheckBeliefFormatResponse.h>


namespace droneMsgsROS
{

struct CheckBeliefFormat
{

typedef CheckBeliefFormatRequest Request;
typedef CheckBeliefFormatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckBeliefFormat
} // namespace droneMsgsROS


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::droneMsgsROS::CheckBeliefFormat > {
  static const char* value()
  {
    return "0950bd055fb30d3ee142f3c8cb406a73";
  }

  static const char* value(const ::droneMsgsROS::CheckBeliefFormat&) { return value(); }
};

template<>
struct DataType< ::droneMsgsROS::CheckBeliefFormat > {
  static const char* value()
  {
    return "droneMsgsROS/CheckBeliefFormat";
  }

  static const char* value(const ::droneMsgsROS::CheckBeliefFormat&) { return value(); }
};


// service_traits::MD5Sum< ::droneMsgsROS::CheckBeliefFormatRequest> should match
// service_traits::MD5Sum< ::droneMsgsROS::CheckBeliefFormat >
template<>
struct MD5Sum< ::droneMsgsROS::CheckBeliefFormatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::droneMsgsROS::CheckBeliefFormat >::value();
  }
  static const char* value(const ::droneMsgsROS::CheckBeliefFormatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::droneMsgsROS::CheckBeliefFormatRequest> should match
// service_traits::DataType< ::droneMsgsROS::CheckBeliefFormat >
template<>
struct DataType< ::droneMsgsROS::CheckBeliefFormatRequest>
{
  static const char* value()
  {
    return DataType< ::droneMsgsROS::CheckBeliefFormat >::value();
  }
  static const char* value(const ::droneMsgsROS::CheckBeliefFormatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::droneMsgsROS::CheckBeliefFormatResponse> should match
// service_traits::MD5Sum< ::droneMsgsROS::CheckBeliefFormat >
template<>
struct MD5Sum< ::droneMsgsROS::CheckBeliefFormatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::droneMsgsROS::CheckBeliefFormat >::value();
  }
  static const char* value(const ::droneMsgsROS::CheckBeliefFormatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::droneMsgsROS::CheckBeliefFormatResponse> should match
// service_traits::DataType< ::droneMsgsROS::CheckBeliefFormat >
template<>
struct DataType< ::droneMsgsROS::CheckBeliefFormatResponse>
{
  static const char* value()
  {
    return DataType< ::droneMsgsROS::CheckBeliefFormat >::value();
  }
  static const char* value(const ::droneMsgsROS::CheckBeliefFormatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRONEMSGSROS_MESSAGE_CHECKBELIEFFORMAT_H
