// Generated by gencpp from file droneMsgsROS/CheckCapabilitiesConsistency.msg
// DO NOT EDIT!


#ifndef DRONEMSGSROS_MESSAGE_CHECKCAPABILITIESCONSISTENCY_H
#define DRONEMSGSROS_MESSAGE_CHECKCAPABILITIESCONSISTENCY_H

#include <ros/service_traits.h>


#include <droneMsgsROS/CheckCapabilitiesConsistencyRequest.h>
#include <droneMsgsROS/CheckCapabilitiesConsistencyResponse.h>


namespace droneMsgsROS
{

struct CheckCapabilitiesConsistency
{

typedef CheckCapabilitiesConsistencyRequest Request;
typedef CheckCapabilitiesConsistencyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckCapabilitiesConsistency
} // namespace droneMsgsROS


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::droneMsgsROS::CheckCapabilitiesConsistency > {
  static const char* value()
  {
    return "df6437565e4e79cd7e32ba2ad3ff1748";
  }

  static const char* value(const ::droneMsgsROS::CheckCapabilitiesConsistency&) { return value(); }
};

template<>
struct DataType< ::droneMsgsROS::CheckCapabilitiesConsistency > {
  static const char* value()
  {
    return "droneMsgsROS/CheckCapabilitiesConsistency";
  }

  static const char* value(const ::droneMsgsROS::CheckCapabilitiesConsistency&) { return value(); }
};


// service_traits::MD5Sum< ::droneMsgsROS::CheckCapabilitiesConsistencyRequest> should match
// service_traits::MD5Sum< ::droneMsgsROS::CheckCapabilitiesConsistency >
template<>
struct MD5Sum< ::droneMsgsROS::CheckCapabilitiesConsistencyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::droneMsgsROS::CheckCapabilitiesConsistency >::value();
  }
  static const char* value(const ::droneMsgsROS::CheckCapabilitiesConsistencyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::droneMsgsROS::CheckCapabilitiesConsistencyRequest> should match
// service_traits::DataType< ::droneMsgsROS::CheckCapabilitiesConsistency >
template<>
struct DataType< ::droneMsgsROS::CheckCapabilitiesConsistencyRequest>
{
  static const char* value()
  {
    return DataType< ::droneMsgsROS::CheckCapabilitiesConsistency >::value();
  }
  static const char* value(const ::droneMsgsROS::CheckCapabilitiesConsistencyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::droneMsgsROS::CheckCapabilitiesConsistencyResponse> should match
// service_traits::MD5Sum< ::droneMsgsROS::CheckCapabilitiesConsistency >
template<>
struct MD5Sum< ::droneMsgsROS::CheckCapabilitiesConsistencyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::droneMsgsROS::CheckCapabilitiesConsistency >::value();
  }
  static const char* value(const ::droneMsgsROS::CheckCapabilitiesConsistencyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::droneMsgsROS::CheckCapabilitiesConsistencyResponse> should match
// service_traits::DataType< ::droneMsgsROS::CheckCapabilitiesConsistency >
template<>
struct DataType< ::droneMsgsROS::CheckCapabilitiesConsistencyResponse>
{
  static const char* value()
  {
    return DataType< ::droneMsgsROS::CheckCapabilitiesConsistency >::value();
  }
  static const char* value(const ::droneMsgsROS::CheckCapabilitiesConsistencyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRONEMSGSROS_MESSAGE_CHECKCAPABILITIESCONSISTENCY_H
