// Generated by gencpp from file droneMsgsROS/configurationFolderResponse.msg
// DO NOT EDIT!


#ifndef DRONEMSGSROS_MESSAGE_CONFIGURATIONFOLDERRESPONSE_H
#define DRONEMSGSROS_MESSAGE_CONFIGURATIONFOLDERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace droneMsgsROS
{
template <class ContainerAllocator>
struct configurationFolderResponse_
{
  typedef configurationFolderResponse_<ContainerAllocator> Type;

  configurationFolderResponse_()
    : folder()  {
    }
  configurationFolderResponse_(const ContainerAllocator& _alloc)
    : folder(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _folder_type;
  _folder_type folder;





  typedef boost::shared_ptr< ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator> const> ConstPtr;

}; // struct configurationFolderResponse_

typedef ::droneMsgsROS::configurationFolderResponse_<std::allocator<void> > configurationFolderResponse;

typedef boost::shared_ptr< ::droneMsgsROS::configurationFolderResponse > configurationFolderResponsePtr;
typedef boost::shared_ptr< ::droneMsgsROS::configurationFolderResponse const> configurationFolderResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator1> & lhs, const ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator2> & rhs)
{
  return lhs.folder == rhs.folder;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator1> & lhs, const ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace droneMsgsROS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf1b291db59c399c5c5b25859bd3e2e3";
  }

  static const char* value(const ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf1b291db59c399cULL;
  static const uint64_t static_value2 = 0x5c5b25859bd3e2e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "droneMsgsROS/configurationFolderResponse";
  }

  static const char* value(const ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string folder \n"
"\n"
;
  }

  static const char* value(const ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.folder);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct configurationFolderResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::droneMsgsROS::configurationFolderResponse_<ContainerAllocator>& v)
  {
    s << indent << "folder: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.folder);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONEMSGSROS_MESSAGE_CONFIGURATIONFOLDERRESPONSE_H
