// Generated by gencpp from file droneMsgsROS/ConsultDefaultBehaviorValuesRequest.msg
// DO NOT EDIT!


#ifndef DRONEMSGSROS_MESSAGE_CONSULTDEFAULTBEHAVIORVALUESREQUEST_H
#define DRONEMSGSROS_MESSAGE_CONSULTDEFAULTBEHAVIORVALUESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace droneMsgsROS
{
template <class ContainerAllocator>
struct ConsultDefaultBehaviorValuesRequest_
{
  typedef ConsultDefaultBehaviorValuesRequest_<ContainerAllocator> Type;

  ConsultDefaultBehaviorValuesRequest_()
    : name()  {
    }
  ConsultDefaultBehaviorValuesRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConsultDefaultBehaviorValuesRequest_

typedef ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<std::allocator<void> > ConsultDefaultBehaviorValuesRequest;

typedef boost::shared_ptr< ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest > ConsultDefaultBehaviorValuesRequestPtr;
typedef boost::shared_ptr< ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest const> ConsultDefaultBehaviorValuesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator1> & lhs, const ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator1> & lhs, const ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace droneMsgsROS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "droneMsgsROS/ConsultDefaultBehaviorValuesRequest";
  }

  static const char* value(const ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This service consults the default values of a behavior\n"
"\n"
"string name           # behavior name\n"
;
  }

  static const char* value(const ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConsultDefaultBehaviorValuesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::droneMsgsROS::ConsultDefaultBehaviorValuesRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONEMSGSROS_MESSAGE_CONSULTDEFAULTBEHAVIORVALUESREQUEST_H
