// Generated by gencpp from file droneMsgsROS/dronePositionRefCommandStamped.msg
// DO NOT EDIT!


#ifndef DRONEMSGSROS_MESSAGE_DRONEPOSITIONREFCOMMANDSTAMPED_H
#define DRONEMSGSROS_MESSAGE_DRONEPOSITIONREFCOMMANDSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <droneMsgsROS/dronePositionRefCommand.h>

namespace droneMsgsROS
{
template <class ContainerAllocator>
struct dronePositionRefCommandStamped_
{
  typedef dronePositionRefCommandStamped_<ContainerAllocator> Type;

  dronePositionRefCommandStamped_()
    : header()
    , position_command()  {
    }
  dronePositionRefCommandStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position_command(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::droneMsgsROS::dronePositionRefCommand_<ContainerAllocator>  _position_command_type;
  _position_command_type position_command;





  typedef boost::shared_ptr< ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator> const> ConstPtr;

}; // struct dronePositionRefCommandStamped_

typedef ::droneMsgsROS::dronePositionRefCommandStamped_<std::allocator<void> > dronePositionRefCommandStamped;

typedef boost::shared_ptr< ::droneMsgsROS::dronePositionRefCommandStamped > dronePositionRefCommandStampedPtr;
typedef boost::shared_ptr< ::droneMsgsROS::dronePositionRefCommandStamped const> dronePositionRefCommandStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator1> & lhs, const ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position_command == rhs.position_command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator1> & lhs, const ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace droneMsgsROS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27182577dabf52f726ecd155be7b8e02";
  }

  static const char* value(const ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27182577dabf52f7ULL;
  static const uint64_t static_value2 = 0x26ecd155be7b8e02ULL;
};

template<class ContainerAllocator>
struct DataType< ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "droneMsgsROS/dronePositionRefCommandStamped";
  }

  static const char* value(const ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Timestamp and sequence number\n"
"Header header\n"
"\n"
"# Position reference\n"
"dronePositionRefCommand position_command\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: droneMsgsROS/dronePositionRefCommand\n"
"#position\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position_command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dronePositionRefCommandStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::droneMsgsROS::dronePositionRefCommandStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position_command: ";
    s << std::endl;
    Printer< ::droneMsgsROS::dronePositionRefCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.position_command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONEMSGSROS_MESSAGE_DRONEPOSITIONREFCOMMANDSTAMPED_H
