// Generated by gencpp from file droneMsgsROS/droneDAltitudeCmd.msg
// DO NOT EDIT!


#ifndef DRONEMSGSROS_MESSAGE_DRONEDALTITUDECMD_H
#define DRONEMSGSROS_MESSAGE_DRONEDALTITUDECMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace droneMsgsROS
{
template <class ContainerAllocator>
struct droneDAltitudeCmd_
{
  typedef droneDAltitudeCmd_<ContainerAllocator> Type;

  droneDAltitudeCmd_()
    : header()
    , dAltitudeCmd(0.0)  {
    }
  droneDAltitudeCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , dAltitudeCmd(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _dAltitudeCmd_type;
  _dAltitudeCmd_type dAltitudeCmd;





  typedef boost::shared_ptr< ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator> const> ConstPtr;

}; // struct droneDAltitudeCmd_

typedef ::droneMsgsROS::droneDAltitudeCmd_<std::allocator<void> > droneDAltitudeCmd;

typedef boost::shared_ptr< ::droneMsgsROS::droneDAltitudeCmd > droneDAltitudeCmdPtr;
typedef boost::shared_ptr< ::droneMsgsROS::droneDAltitudeCmd const> droneDAltitudeCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator1> & lhs, const ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.dAltitudeCmd == rhs.dAltitudeCmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator1> & lhs, const ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace droneMsgsROS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a7a76c9b30bdcf4e6130e25d5fc7b37";
  }

  static const char* value(const ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a7a76c9b30bdcf4ULL;
  static const uint64_t static_value2 = 0xe6130e25d5fc7b37ULL;
};

template<class ContainerAllocator>
struct DataType< ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "droneMsgsROS/droneDAltitudeCmd";
  }

  static const char* value(const ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#header\n"
"Header header\n"
"\n"
"#command\n"
"float64 dAltitudeCmd\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.dAltitudeCmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct droneDAltitudeCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::droneMsgsROS::droneDAltitudeCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "dAltitudeCmd: ";
    Printer<double>::stream(s, indent + "  ", v.dAltitudeCmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONEMSGSROS_MESSAGE_DRONEDALTITUDECMD_H
