// Generated by gencpp from file droneMsgsROS/InhibitBehaviorRequest.msg
// DO NOT EDIT!


#ifndef DRONEMSGSROS_MESSAGE_INHIBITBEHAVIORREQUEST_H
#define DRONEMSGSROS_MESSAGE_INHIBITBEHAVIORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace droneMsgsROS
{
template <class ContainerAllocator>
struct InhibitBehaviorRequest_
{
  typedef InhibitBehaviorRequest_<ContainerAllocator> Type;

  InhibitBehaviorRequest_()
    : behavior_uid(0.0)  {
    }
  InhibitBehaviorRequest_(const ContainerAllocator& _alloc)
    : behavior_uid(0.0)  {
  (void)_alloc;
    }



   typedef double _behavior_uid_type;
  _behavior_uid_type behavior_uid;





  typedef boost::shared_ptr< ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InhibitBehaviorRequest_

typedef ::droneMsgsROS::InhibitBehaviorRequest_<std::allocator<void> > InhibitBehaviorRequest;

typedef boost::shared_ptr< ::droneMsgsROS::InhibitBehaviorRequest > InhibitBehaviorRequestPtr;
typedef boost::shared_ptr< ::droneMsgsROS::InhibitBehaviorRequest const> InhibitBehaviorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator1> & lhs, const ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator2> & rhs)
{
  return lhs.behavior_uid == rhs.behavior_uid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator1> & lhs, const ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace droneMsgsROS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2da4977292dd43c9fd64c5a8e925785";
  }

  static const char* value(const ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2da4977292dd43cULL;
  static const uint64_t static_value2 = 0x9fd64c5a8e925785ULL;
};

template<class ContainerAllocator>
struct DataType< ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "droneMsgsROS/InhibitBehaviorRequest";
  }

  static const char* value(const ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This service inhibits a behavior\n"
"\n"
"float64 behavior_uid       # The UID of the behavior to inhibit\n"
;
  }

  static const char* value(const ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.behavior_uid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InhibitBehaviorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::droneMsgsROS::InhibitBehaviorRequest_<ContainerAllocator>& v)
  {
    s << indent << "behavior_uid: ";
    Printer<double>::stream(s, indent + "  ", v.behavior_uid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONEMSGSROS_MESSAGE_INHIBITBEHAVIORREQUEST_H
