// Generated by gencpp from file droneMsgsROS/obstacleTwoDimWall.msg
// DO NOT EDIT!


#ifndef DRONEMSGSROS_MESSAGE_OBSTACLETWODIMWALL_H
#define DRONEMSGSROS_MESSAGE_OBSTACLETWODIMWALL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace droneMsgsROS
{
template <class ContainerAllocator>
struct obstacleTwoDimWall_
{
  typedef obstacleTwoDimWall_<ContainerAllocator> Type;

  obstacleTwoDimWall_()
    : id(0)
    , centerX(0.0)
    , centerY(0.0)
    , sizeX(0.0)
    , sizeY(0.0)
    , yawAngle(0.0)
    , isVirtual(false)  {
    }
  obstacleTwoDimWall_(const ContainerAllocator& _alloc)
    : id(0)
    , centerX(0.0)
    , centerY(0.0)
    , sizeX(0.0)
    , sizeY(0.0)
    , yawAngle(0.0)
    , isVirtual(false)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef float _centerX_type;
  _centerX_type centerX;

   typedef float _centerY_type;
  _centerY_type centerY;

   typedef float _sizeX_type;
  _sizeX_type sizeX;

   typedef float _sizeY_type;
  _sizeY_type sizeY;

   typedef float _yawAngle_type;
  _yawAngle_type yawAngle;

   typedef uint8_t _isVirtual_type;
  _isVirtual_type isVirtual;





  typedef boost::shared_ptr< ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator> const> ConstPtr;

}; // struct obstacleTwoDimWall_

typedef ::droneMsgsROS::obstacleTwoDimWall_<std::allocator<void> > obstacleTwoDimWall;

typedef boost::shared_ptr< ::droneMsgsROS::obstacleTwoDimWall > obstacleTwoDimWallPtr;
typedef boost::shared_ptr< ::droneMsgsROS::obstacleTwoDimWall const> obstacleTwoDimWallConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator1> & lhs, const ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.centerX == rhs.centerX &&
    lhs.centerY == rhs.centerY &&
    lhs.sizeX == rhs.sizeX &&
    lhs.sizeY == rhs.sizeY &&
    lhs.yawAngle == rhs.yawAngle &&
    lhs.isVirtual == rhs.isVirtual;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator1> & lhs, const ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace droneMsgsROS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d82de645b9a720aeec691a05387e1f6";
  }

  static const char* value(const ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d82de645b9a720aULL;
  static const uint64_t static_value2 = 0xeec691a05387e1f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "droneMsgsROS/obstacleTwoDimWall";
  }

  static const char* value(const ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#id\n"
"int32 id\n"
"\n"
"#position of the center of the obstacle\n"
"float32 centerX\n"
"float32 centerY\n"
"\n"
"#sizes\n"
"float32 sizeX\n"
"float32 sizeY\n"
"\n"
"\n"
"#yaw angle\n"
"float32 yawAngle\n"
"\n"
"\n"
"# flag to determine if the obstacle is real or virtual\n"
"bool isVirtual\n"
"\n"
;
  }

  static const char* value(const ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.centerX);
      stream.next(m.centerY);
      stream.next(m.sizeX);
      stream.next(m.sizeY);
      stream.next(m.yawAngle);
      stream.next(m.isVirtual);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct obstacleTwoDimWall_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::droneMsgsROS::obstacleTwoDimWall_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "centerX: ";
    Printer<float>::stream(s, indent + "  ", v.centerX);
    s << indent << "centerY: ";
    Printer<float>::stream(s, indent + "  ", v.centerY);
    s << indent << "sizeX: ";
    Printer<float>::stream(s, indent + "  ", v.sizeX);
    s << indent << "sizeY: ";
    Printer<float>::stream(s, indent + "  ", v.sizeY);
    s << indent << "yawAngle: ";
    Printer<float>::stream(s, indent + "  ", v.yawAngle);
    s << indent << "isVirtual: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isVirtual);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONEMSGSROS_MESSAGE_OBSTACLETWODIMWALL_H
