// Generated by gencpp from file droneMsgsROS/points3DStamped.msg
// DO NOT EDIT!


#ifndef DRONEMSGSROS_MESSAGE_POINTS3DSTAMPED_H
#define DRONEMSGSROS_MESSAGE_POINTS3DSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <droneMsgsROS/vector3f.h>

namespace droneMsgsROS
{
template <class ContainerAllocator>
struct points3DStamped_
{
  typedef points3DStamped_<ContainerAllocator> Type;

  points3DStamped_()
    : header()
    , points3D()  {
    }
  points3DStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , points3D(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::droneMsgsROS::vector3f_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::droneMsgsROS::vector3f_<ContainerAllocator> >::other >  _points3D_type;
  _points3D_type points3D;





  typedef boost::shared_ptr< ::droneMsgsROS::points3DStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::droneMsgsROS::points3DStamped_<ContainerAllocator> const> ConstPtr;

}; // struct points3DStamped_

typedef ::droneMsgsROS::points3DStamped_<std::allocator<void> > points3DStamped;

typedef boost::shared_ptr< ::droneMsgsROS::points3DStamped > points3DStampedPtr;
typedef boost::shared_ptr< ::droneMsgsROS::points3DStamped const> points3DStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::droneMsgsROS::points3DStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::droneMsgsROS::points3DStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::droneMsgsROS::points3DStamped_<ContainerAllocator1> & lhs, const ::droneMsgsROS::points3DStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.points3D == rhs.points3D;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::droneMsgsROS::points3DStamped_<ContainerAllocator1> & lhs, const ::droneMsgsROS::points3DStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace droneMsgsROS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::points3DStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::points3DStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::points3DStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::points3DStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::points3DStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::points3DStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::droneMsgsROS::points3DStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deffe1da96b3d2650971859bcc1ef55a";
  }

  static const char* value(const ::droneMsgsROS::points3DStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdeffe1da96b3d265ULL;
  static const uint64_t static_value2 = 0x0971859bcc1ef55aULL;
};

template<class ContainerAllocator>
struct DataType< ::droneMsgsROS::points3DStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "droneMsgsROS/points3DStamped";
  }

  static const char* value(const ::droneMsgsROS::points3DStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::droneMsgsROS::points3DStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"#header\n"
"Header header\n"
"\n"
"#vector of points in the 3D space\n"
"vector3f[] points3D\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: droneMsgsROS/vector3f\n"
"#This message has the information of a 3D point (float)\n"
"\n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"\n"
;
  }

  static const char* value(const ::droneMsgsROS::points3DStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::droneMsgsROS::points3DStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.points3D);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct points3DStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::droneMsgsROS::points3DStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::droneMsgsROS::points3DStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "points3D[]" << std::endl;
    for (size_t i = 0; i < v.points3D.size(); ++i)
    {
      s << indent << "  points3D[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::droneMsgsROS::vector3f_<ContainerAllocator> >::stream(s, indent + "    ", v.points3D[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONEMSGSROS_MESSAGE_POINTS3DSTAMPED_H
