// Generated by gencpp from file droneMsgsROS/robotPoseVector.msg
// DO NOT EDIT!


#ifndef DRONEMSGSROS_MESSAGE_ROBOTPOSEVECTOR_H
#define DRONEMSGSROS_MESSAGE_ROBOTPOSEVECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <droneMsgsROS/robotPose.h>

namespace droneMsgsROS
{
template <class ContainerAllocator>
struct robotPoseVector_
{
  typedef robotPoseVector_<ContainerAllocator> Type;

  robotPoseVector_()
    : header()
    , robot_pose_vector()  {
    }
  robotPoseVector_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_pose_vector(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::droneMsgsROS::robotPose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::droneMsgsROS::robotPose_<ContainerAllocator> >::other >  _robot_pose_vector_type;
  _robot_pose_vector_type robot_pose_vector;





  typedef boost::shared_ptr< ::droneMsgsROS::robotPoseVector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::droneMsgsROS::robotPoseVector_<ContainerAllocator> const> ConstPtr;

}; // struct robotPoseVector_

typedef ::droneMsgsROS::robotPoseVector_<std::allocator<void> > robotPoseVector;

typedef boost::shared_ptr< ::droneMsgsROS::robotPoseVector > robotPoseVectorPtr;
typedef boost::shared_ptr< ::droneMsgsROS::robotPoseVector const> robotPoseVectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::droneMsgsROS::robotPoseVector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::droneMsgsROS::robotPoseVector_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::droneMsgsROS::robotPoseVector_<ContainerAllocator1> & lhs, const ::droneMsgsROS::robotPoseVector_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.robot_pose_vector == rhs.robot_pose_vector;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::droneMsgsROS::robotPoseVector_<ContainerAllocator1> & lhs, const ::droneMsgsROS::robotPoseVector_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace droneMsgsROS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::robotPoseVector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::robotPoseVector_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::robotPoseVector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::robotPoseVector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::robotPoseVector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::robotPoseVector_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::droneMsgsROS::robotPoseVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a61388567552e8a86c524e7001dcbee";
  }

  static const char* value(const ::droneMsgsROS::robotPoseVector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a61388567552e8aULL;
  static const uint64_t static_value2 = 0x86c524e7001dcbeeULL;
};

template<class ContainerAllocator>
struct DataType< ::droneMsgsROS::robotPoseVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "droneMsgsROS/robotPoseVector";
  }

  static const char* value(const ::droneMsgsROS::robotPoseVector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::droneMsgsROS::robotPoseVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Message Header\n"
"Header header\n"
"\n"
"# vector of detected/tracker robots\n"
"robotPose[] robot_pose_vector\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: droneMsgsROS/robotPose\n"
"# position of the target_frame\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"\n"
"#attitude of the target_frame\n"
"float32 theta \n"
"\n"
"#id of Robot\n"
"int32 id_Robot\n"
"int32 Robot_Type\n"
"\n"
"\n"
;
  }

  static const char* value(const ::droneMsgsROS::robotPoseVector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::droneMsgsROS::robotPoseVector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_pose_vector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotPoseVector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::droneMsgsROS::robotPoseVector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::droneMsgsROS::robotPoseVector_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_pose_vector[]" << std::endl;
    for (size_t i = 0; i < v.robot_pose_vector.size(); ++i)
    {
      s << indent << "  robot_pose_vector[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::droneMsgsROS::robotPose_<ContainerAllocator> >::stream(s, indent + "    ", v.robot_pose_vector[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONEMSGSROS_MESSAGE_ROBOTPOSEVECTOR_H
