// Generated by gencpp from file droneMsgsROS/seg.msg
// DO NOT EDIT!


#ifndef DRONEMSGSROS_MESSAGE_SEG_H
#define DRONEMSGSROS_MESSAGE_SEG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace droneMsgsROS
{
template <class ContainerAllocator>
struct seg_
{
  typedef seg_<ContainerAllocator> Type;

  seg_()
    : p()  {
    }
  seg_(const ContainerAllocator& _alloc)
    : p(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _p_type;
  _p_type p;





  typedef boost::shared_ptr< ::droneMsgsROS::seg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::droneMsgsROS::seg_<ContainerAllocator> const> ConstPtr;

}; // struct seg_

typedef ::droneMsgsROS::seg_<std::allocator<void> > seg;

typedef boost::shared_ptr< ::droneMsgsROS::seg > segPtr;
typedef boost::shared_ptr< ::droneMsgsROS::seg const> segConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::droneMsgsROS::seg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::droneMsgsROS::seg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::droneMsgsROS::seg_<ContainerAllocator1> & lhs, const ::droneMsgsROS::seg_<ContainerAllocator2> & rhs)
{
  return lhs.p == rhs.p;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::droneMsgsROS::seg_<ContainerAllocator1> & lhs, const ::droneMsgsROS::seg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace droneMsgsROS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::seg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::droneMsgsROS::seg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::seg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::droneMsgsROS::seg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::seg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::droneMsgsROS::seg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::droneMsgsROS::seg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2bc9ec58afd3958ddfccccd825801682";
  }

  static const char* value(const ::droneMsgsROS::seg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2bc9ec58afd3958dULL;
  static const uint64_t static_value2 = 0xdfccccd825801682ULL;
};

template<class ContainerAllocator>
struct DataType< ::droneMsgsROS::seg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "droneMsgsROS/seg";
  }

  static const char* value(const ::droneMsgsROS::seg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::droneMsgsROS::seg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] p\n"
;
  }

  static const char* value(const ::droneMsgsROS::seg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::droneMsgsROS::seg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct seg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::droneMsgsROS::seg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::droneMsgsROS::seg_<ContainerAllocator>& v)
  {
    s << indent << "p[]" << std::endl;
    for (size_t i = 0; i < v.p.size(); ++i)
    {
      s << indent << "  p[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.p[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONEMSGSROS_MESSAGE_SEG_H
