// Generated by gencpp from file droneMsgsROS/setControlMode.msg
// DO NOT EDIT!


#ifndef DRONEMSGSROS_MESSAGE_SETCONTROLMODE_H
#define DRONEMSGSROS_MESSAGE_SETCONTROLMODE_H

#include <ros/service_traits.h>


#include <droneMsgsROS/setControlModeRequest.h>
#include <droneMsgsROS/setControlModeResponse.h>


namespace droneMsgsROS
{

struct setControlMode
{

typedef setControlModeRequest Request;
typedef setControlModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setControlMode
} // namespace droneMsgsROS


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::droneMsgsROS::setControlMode > {
  static const char* value()
  {
    return "a6b22d0b26c8f8715cf358d316c5a75a";
  }

  static const char* value(const ::droneMsgsROS::setControlMode&) { return value(); }
};

template<>
struct DataType< ::droneMsgsROS::setControlMode > {
  static const char* value()
  {
    return "droneMsgsROS/setControlMode";
  }

  static const char* value(const ::droneMsgsROS::setControlMode&) { return value(); }
};


// service_traits::MD5Sum< ::droneMsgsROS::setControlModeRequest> should match
// service_traits::MD5Sum< ::droneMsgsROS::setControlMode >
template<>
struct MD5Sum< ::droneMsgsROS::setControlModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::droneMsgsROS::setControlMode >::value();
  }
  static const char* value(const ::droneMsgsROS::setControlModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::droneMsgsROS::setControlModeRequest> should match
// service_traits::DataType< ::droneMsgsROS::setControlMode >
template<>
struct DataType< ::droneMsgsROS::setControlModeRequest>
{
  static const char* value()
  {
    return DataType< ::droneMsgsROS::setControlMode >::value();
  }
  static const char* value(const ::droneMsgsROS::setControlModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::droneMsgsROS::setControlModeResponse> should match
// service_traits::MD5Sum< ::droneMsgsROS::setControlMode >
template<>
struct MD5Sum< ::droneMsgsROS::setControlModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::droneMsgsROS::setControlMode >::value();
  }
  static const char* value(const ::droneMsgsROS::setControlModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::droneMsgsROS::setControlModeResponse> should match
// service_traits::DataType< ::droneMsgsROS::setControlMode >
template<>
struct DataType< ::droneMsgsROS::setControlModeResponse>
{
  static const char* value()
  {
    return DataType< ::droneMsgsROS::setControlMode >::value();
  }
  static const char* value(const ::droneMsgsROS::setControlModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRONEMSGSROS_MESSAGE_SETCONTROLMODE_H
