// Generated by gencpp from file droneMsgsROS/setInitDroneYaw_srv_type.msg
// DO NOT EDIT!


#ifndef DRONEMSGSROS_MESSAGE_SETINITDRONEYAW_SRV_TYPE_H
#define DRONEMSGSROS_MESSAGE_SETINITDRONEYAW_SRV_TYPE_H

#include <ros/service_traits.h>


#include <droneMsgsROS/setInitDroneYaw_srv_typeRequest.h>
#include <droneMsgsROS/setInitDroneYaw_srv_typeResponse.h>


namespace droneMsgsROS
{

struct setInitDroneYaw_srv_type
{

typedef setInitDroneYaw_srv_typeRequest Request;
typedef setInitDroneYaw_srv_typeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setInitDroneYaw_srv_type
} // namespace droneMsgsROS


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::droneMsgsROS::setInitDroneYaw_srv_type > {
  static const char* value()
  {
    return "298f36d3955b3d30628dd57245c8b658";
  }

  static const char* value(const ::droneMsgsROS::setInitDroneYaw_srv_type&) { return value(); }
};

template<>
struct DataType< ::droneMsgsROS::setInitDroneYaw_srv_type > {
  static const char* value()
  {
    return "droneMsgsROS/setInitDroneYaw_srv_type";
  }

  static const char* value(const ::droneMsgsROS::setInitDroneYaw_srv_type&) { return value(); }
};


// service_traits::MD5Sum< ::droneMsgsROS::setInitDroneYaw_srv_typeRequest> should match
// service_traits::MD5Sum< ::droneMsgsROS::setInitDroneYaw_srv_type >
template<>
struct MD5Sum< ::droneMsgsROS::setInitDroneYaw_srv_typeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::droneMsgsROS::setInitDroneYaw_srv_type >::value();
  }
  static const char* value(const ::droneMsgsROS::setInitDroneYaw_srv_typeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::droneMsgsROS::setInitDroneYaw_srv_typeRequest> should match
// service_traits::DataType< ::droneMsgsROS::setInitDroneYaw_srv_type >
template<>
struct DataType< ::droneMsgsROS::setInitDroneYaw_srv_typeRequest>
{
  static const char* value()
  {
    return DataType< ::droneMsgsROS::setInitDroneYaw_srv_type >::value();
  }
  static const char* value(const ::droneMsgsROS::setInitDroneYaw_srv_typeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::droneMsgsROS::setInitDroneYaw_srv_typeResponse> should match
// service_traits::MD5Sum< ::droneMsgsROS::setInitDroneYaw_srv_type >
template<>
struct MD5Sum< ::droneMsgsROS::setInitDroneYaw_srv_typeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::droneMsgsROS::setInitDroneYaw_srv_type >::value();
  }
  static const char* value(const ::droneMsgsROS::setInitDroneYaw_srv_typeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::droneMsgsROS::setInitDroneYaw_srv_typeResponse> should match
// service_traits::DataType< ::droneMsgsROS::setInitDroneYaw_srv_type >
template<>
struct DataType< ::droneMsgsROS::setInitDroneYaw_srv_typeResponse>
{
  static const char* value()
  {
    return DataType< ::droneMsgsROS::setInitDroneYaw_srv_type >::value();
  }
  static const char* value(const ::droneMsgsROS::setInitDroneYaw_srv_typeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRONEMSGSROS_MESSAGE_SETINITDRONEYAW_SRV_TYPE_H
