(cl:in-package droneMsgsROS-srv)
(cl:export '(CAPABILITIES_TO_ACTIVATE-VAL
          CAPABILITIES_TO_ACTIVATE
          ACTIVE_CAPABILITIES-VAL
          ACTIVE_CAPABILITIES
          CONSISTENT-VAL
          CONSISTENT
          ERROR_MESSAGE-VAL
          ERROR_MESSAGE
          INCONSISTENT_CAPABILITIES-VAL
          INCONSISTENT_CAPABILITIES
))